steps:
  # build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/zerotreedelta-ui', '.']
  
  # push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/zerotreedelta-ui']
  
  # Deploy container image to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'run', 'deploy', 'zerotreedelta-ui', '--image', 'gcr.io/$PROJECT_ID/zerotreedelta-ui', '--region', 'us-central1']
images:
- gcr.io/$PROJECT_ID/zerotreedelta-ui